### PR TITLE
Add Malay translation .

### PR DESCRIPTION
**Pull request by codegateau**
GoodLuck :)

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Thank you!

**Comment by codegateau** [comment]
Label it as Hacktoberfest?

**Comment by rodrigo-brito** [comment]
Any contributing in october is valid for hacktoberfest. The label isn't necessary. I've confirmed my shirt without label. The label was used only for identify the projects in the event.

**Comment by rodrigo-brito** [comment]
But, no problem. I can do it.

**Comment by codegateau** [comment]
I've add a translation to your FireTODOlist project too

**Pull request merged**
